Repository rust-lang/book, pull requests merged in 2024-04, with the labels that each got.

#3874 Fix a typo: remove an extra 's' from ch. 18.01
  src/ch08-01-vectors.md
Labels: 2024-edition-update

#3780 Small correction in ch13-01
  listings/ch13-functional-features/listing-13-08/output.txt
  listings/ch13-functional-features/listing-13-08/src/main.rs
  src/ch13-01-closures.md
Labels: 2024-fix-nomination

#3767 Update panic! formatting style for Guess example
  listings/ch09-error-handling/listing-09-13/src/main.rs
  listings/ch11-writing-automated-tests/listing-11-08/src/lib.rs
  listings/ch11-writing-automated-tests/listing-11-09/src/lib.rs
  listings/ch11-writing-automated-tests/no-listing-08-guess-with-bug/src/lib.rs
  listings/ch11-writing-automated-tests/no-listing-09-guess-with-panic-msg-bug/src/lib.rs
Labels: 2024-fix-nomination

#3876 Make Note text in ch. 20 consistent with other notes
  src/ch20-02-multithreaded.md
Labels: 2024-fix-nomination

#3857 Update full code reference main.rs in ch20-03
  listings/ch20-web-server/listing-20-25/src/main.rs
  listings/ch20-web-server/no-listing-07-final-code/src/main.rs
Labels: S-waiting-on-author

#3790 Minor text improvements
  src/appendix-03-derivable-traits.md
Labels: S-waiting-on-author

#3879 Ch. 7: add a note about the need for `pub` in one more place
  src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
Labels: 2024-edition-update

#3546 Replace RLS with rust-analyzer in ch00
  src/ch00-00-introduction.md
Labels: 2024-fix-nomination

#3616 Update MSVC instructions
  src/ch01-01-installation.md
Labels: S-waiting-on-author
